In [1]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [2]:
import numpy as np
 
arr1=np.array([1,2,3,4])   # 1D
print(arr1)
arr2d=np.array(
   [ [1,2],[3,4]])   #2D
print (arr2d)

[1 2 3 4]
[[1 2]
 [3 4]]


In [8]:
import numpy as np

print(arr1.shape)
print(arr2d.shape)   #shape attribute

print("-----------------")
print(arr1)
print(arr1.shape)            # (or) c=np.shape(arr1)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)
print("-----------------")
print(arr2d)
print(arr2d.shape)    # Shape (rows, columns)
print(arr2d.ndim)   # Number of dimensions
print(arr2d.size)  # Total elements
print(arr2d.dtype)  # Data type

(4,)
(2, 2)
-----------------
[1 2 3 4]
(4,)
1
4
int64
-----------------
[[1 2]
 [3 4]]
(2, 2)
2
4
int64


In [2]:
#Mathematical operations
import numpy as np
a = np.array([1, 2, 3])

print(a + 2)     # Add 2 to each element
print(a * 3)     # Multiply each element

[3 4 5]
[3 6 9]


In [3]:
# Sum, Mean, Max, Min
import numpy as np

a=[1,6,5]
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.max(a))
print(np.min(a))

12
4.0
5.0
6
1


In [6]:
#Flattening
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)
print(b.flatten())



[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [7]:
#Adding & Deleting Elements
import numpy as np

a = np.array([1, 2, 3])

a = np.append(a, 4)
print(a)

a = np.delete(a, 1)   # delete index 1
print(a)

[1 2 3 4]
[1 3 4]


In [8]:
#Sorting
import numpy as np
a = np.array([5, 2, 8, 1])
print(np.sort(a))

[1 2 5 8]


In [9]:
import numpy as np
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([10,20,30,40,50,60])
print("array 1=",arr1,"\n array 2=",arr2)

addarr=arr1+arr2 
print(addarr)
subarr=arr2-arr1
print(subarr)
mularr=arr1*arr2   
print(mularr)

array 1= [1 2 3 4 5 6] 
 array 2= [10 20 30 40 50 60]
[11 22 33 44 55 66]
[ 9 18 27 36 45 54]
[ 10  40  90 160 250 360]


In [11]:
# 2D array
a1=np.array([
    [1,2,3],
    [4,5,6]
])

print(a1)
a2=np.array([
    [10,20,30],[40,50,60]
])
print(a2)

adda=a1+a2
print(adda)
mula=a1*a2   
print(mula)

[[1 2 3]
 [4 5 6]]
[[10 20 30]
 [40 50 60]]
[[11 22 33]
 [44 55 66]]
[[ 10  40  90]
 [160 250 360]]


In [14]:
# Matrix multiplication
import numpy as np

matA=np.array([[1,2,3],[4,5,6]])
matB=np.array([[2,2,2],[3,3,3],[4,4,4]])
print("Mat A\n",matA,"\n MatB:\n",matB)
print("\n")
print(np.shape(matA))
print(np.shape(matB))

productAB=np.dot(matA,matB)
print(productAB)

Mat A
 [[1 2 3]
 [4 5 6]] 
 MatB:
 [[2 2 2]
 [3 3 3]
 [4 4 4]]


(2, 3)
(3, 3)
[[20 20 20]
 [47 47 47]]


In [15]:
prod=np.dot(a1,a2.T)    # Transpose a2   shape 2 x 3 , 3 x 2 => 3=3
print(a1,"\n",a2)
print("transpose a2:\n")
print(a1,"\n",a2.T)
print("\nproduct")
print(prod)

[[1 2 3]
 [4 5 6]] 
 [[10 20 30]
 [40 50 60]]
transpose a2:

[[1 2 3]
 [4 5 6]] 
 [[10 40]
 [20 50]
 [30 60]]

product
[[140 320]
 [320 770]]


In [16]:
m=[[1,2,3],[4,5,6]]
mT=np.transpose(m)
print(mT)

[[1 4]
 [2 5]
 [3 6]]


In [19]:
m1=[[1,2,3],[4,5,6]]
m2=[[10,20,30],[40,50,60]]

print(m1)
print(m2)

m=np.add(m1,m2)
print(m)
m=np.subtract(m1,m2)
print(m)
m=np.multiply(m1,m2)
print(m)
m=np.transpose(m1)
print(m)
m=np.transpose(m2)
print(m)

[[1, 2, 3], [4, 5, 6]]
[[10, 20, 30], [40, 50, 60]]
[[11 22 33]
 [44 55 66]]
[[ -9 -18 -27]
 [-36 -45 -54]]
[[ 10  40  90]
 [160 250 360]]
[[1 4]
 [2 5]
 [3 6]]
[[10 40]
 [20 50]
 [30 60]]
